# marginal pmf mixture model

# sample i, bin j, component k

# v_j value in bin j
# c_{ij} observed count in bin j of sample i,  n_i = \sum_j c_{ij}
# z_{ijk} latent count in bin j of sample i generated by component k
# w_{ik}  mixing proportions
# \theta = ((\mu_k), (\psi_k))  distributional parameters for each component

# p(Z \mid W, \theta) \propto
#   \prod_i^N \prod_j^J \prod_k^K
#     ( w_{ik} f(v_j \mid \theta_k) )^{z_{ijk}}

# update equations

# \gamma_{ijk} 
#  = w_{ik} f(v_j \mid \theta_k) / ( \sum_k w_{ik} f(v_j \mid \theta_k) )

# \hat{z_{ijk}} 
#  = E[ z_{ijk} \mid c_{ij}, \theta ] 
#  = c_{ij} \gamma_{ijk}

# w_{ik}
#  = (\alpha_k - 1 + \sum_j \hat{z_{ijk}}) / (n_i - K \sum_k \alpha_k)

# Q(\theta) = E_Z[ \log p(C, \theta, Z) ]
#   = \log p(\theta) + \log p(w) +
#     \sum_i \sum_j \sum_k \hat{z_{ijk}} \log f(v_j \mid \theta_k)


pmfmix_initialize <- function(C, v, K, f, initialize_theta, hparams, fixed) {
  N <- nrow(C)

  if (is.null(fixed$w)) {
    w <- matrix(runif(N * K), N, K)
    w <- w / rowSums(w)
  } else {
    w <- fixed$w
  }

  if (is.null(fixed$theta)) {
    theta <- initialize_theta(C, v, K, hparams)
  } else {
    theta <- fixed$theta
  }

  list(w = w, theta = theta)
}

pmfmix_opt <- function(C, v, params, f, update_theta, hparams, control,
                       fixed, log_prior_theta, verbose = TRUE) {
  obj.old <- -Inf
  if (is.null(fixed$f)) {
    params$f <- pmfmix_update_f(f, v, params);
  }
  for (iter in 1:control$niter) {
    if (is.null(fixed$Gamma)) {
      params$Gamma <- pmfmix_update_gamma(C, params);
    }
    if (is.null(fixed$z)) {
      params$z <- pmfmix_update_z(C, params);
    }
    if (is.null(fixed$w)) {
      params$w <- pmfmix_update_w(params, hparams);
    }
    if (is.null(fixed$theta)) {
      params$theta <- update_theta(C, v, params, hparams)
    }
    if (is.null(fixed$f)) {
      params$f <- pmfmix_update_f(f, v, params);
    }
    obj <- pmfmix_obj(C, params, hparams, log_prior_theta)
    if (verbose) {
      message("iter: ", iter, ", objective: ", obj)
    }
    if (obj - obj.old < control$abstol) {
      break
    }
    obj.old <- obj
  }

  list(lp = obj, iter = iter, params = params)
}

pmfmix <- function(C, v, K, f, update_theta, initialize_theta,
                   hparams = NULL, control = NULL, control2 = NULL, fixed = NULL,
                   log_prior_theta = NULL, verbose = TRUE) {
  stime <- proc.time();

  if (is.vector(C)) {
    C <- matrix(C, nrow = 1);
  }

  J <- ncol(C);

  hparams.default <- list(alpha = rep(1, K));
  hparams <- c(hparams, hparams.default);

  control.default <- list(
    nstart = 5,
    niter = 20,
    abstol = 1e-3
  )
  control <- c(control, control.default);

  control2.default <- list(
    niter = 100,
    abstol = 1e-6
  )
  control2 <- c(control2, control2.default);

  res <- lapply(1:control$nstart, function(b) {
    if (verbose) message("start ", b)
    params <- pmfmix_initialize(C, v, K, f, initialize_theta, hparams, fixed);
    pmfmix_opt(C, v, params, f, update_theta, hparams, control, fixed,
               log_prior_theta, verbose = verbose);
  });

  lps <- vapply(res, function(x) x$lp, -Inf);
  opt <- res[[which.max(lps)]];
  if (verbose) {
    message("expected log joint probs: ", paste(format(lps, digits = 2), collapse = ", "))
  }

  opt2 <- pmfmix_opt(C, v, opt$params, f, update_theta, hparams, control2, fixed,
                     log_prior_theta, verbose = verbose);
  opt2$iter <- c(opt$iter, opt2$iter);

  if (verbose) {
    message("Elapsed time: ", proc.time()[3] - stime[3])
  }

  structure(opt2, class = "pmfmix")
}

# depends on f
pmfmix_update_gamma <- function(C, params) {
  N <- nrow(C);
  J <- ncol(C);
  K <- ncol(params$w);

  Gamma <- array(0, c(N, J, K));
  for (i in 1:N) {
    for (j in 1:J) {
      s <- 0
      for (k in 1:K) {
        Gamma[i, j, k] <- params$w[i, k] * params$f[[k]][j];
        s <- s + Gamma[i, j, k];
      }
      Gamma[i, j, ] <- Gamma[i, j, ] / s;
    }
  }
  Gamma
}

pmfmix_update_z <- function(C, params) {
  N <- nrow(C);
  J <- ncol(C);
  K <- ncol(params$w);
  z <- array(0, c(N, J, K));
  for (i in 1:N) {
    for (k in 1:K) {
      z[i, , k] <- C[i, ] * params$Gamma[i, , k];
    }
  }
  z
}

pmfmix_update_w <- function(params, hparams) {
  N <- nrow(params$w);
  K <- ncol(params$w);

  w <- matrix(0, N, K);
  for (i in 1:N) {
    for (k in 1:K) {
      w[i, k] <- sum(params$z[i, , k]) + hparams$alpha[k] - 1;
    }
  }
  w / rowSums(w)
}

pmfmix_update_f <- function(f, v, params) {
  lapply(params$theta, function(theta) {
    pmf <- f(v, theta);
    pmf / sum(pmf)
  })
}

pmfmix_obj <- function(C, params, hparams, log_prior_theta = NULL) {
  lp_w <- sum((hparams$alpha - 1) * log(t(params$w)));

  lp_theta <- 0;
  if (!is.null(log_prior_theta)) {
    lp_theta <- log_prior_theta(params$theta, hparams);
  }

  N <- nrow(C);
  J <- ncol(C);
  K <- length(params$theta);

  ll <- 0;
  for (i in 1:N) {
    for (j in 1:J) {
      if (C[i, j] > 0) {
        for (k in 1:K) {
          # guard against 0 * log(0) = NaN
          # here, 0 * log(0) = 0
          if (params$z[i, j, k] > 0) {
            ll <- ll + with(params,
              z[i, j, k] * log(w[i, k] * f[[k]][j])
            );
          }
        }
      }
    }
  }

  lp_w + lp_theta + ll
}
