# marginal pmf mixture model

# sample i, bin j, component k

# v_j value in bin j
# c_{ij} observed count in bin j of sample i,  n_i = \sum_j c_{ij}
# z_{ijk} latent count in bin j of sample i generated by component k
# w_{ik}  mixing proportions
# \theta = (\mu_k, \psi_k)  distributional parameters for each component

# p(Z \mid W, \mu, \psi) \propto
#   \prod_i^N \prod_j^J \prod_k^K
#     ( w_{ik} f(v_j \mid \theta_k) )^{z_{ijk})

# update equations

# \gamma_{ijk} 
#  = w_{ik} f(v_j \mid \theta_k) / ( \sum_k w_{ik} f(v_j \mid \theta_k) )

# \hat{z_{ijk}} 
#  = E[ z_{ijk} \mid c_{ij}, \theta ] 
#  = c_{ij} \gamma_{ijk}

# w_{ik}
#  = (\sum_j \hat{z_{ijk}} + \alpha_k - 1) / (n_i + \sum_k \alpha_k - 1)

# Q(\theta) = E_Z[ \log p(C, \theta, Z) ]
#   = \log p(\theta) + 
#     \sum_i \sum_j \sum_k \hat{z_{ijk}} \log f(v_j \mid \theta_k)

